#!/bin/bash
echo "deb http://debian.repo.frc.s3.amazonaws.com jessie main" | sudo tee -a /etc/apt/sources.list
wget -O - http://debian.repo.frc.s3.amazonaws.com/rbmj.gpg.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install cmake gcc-powerpc-wrs-vxworks frc-buildscripts wpilib frcmake
echo "export WIND_BASE=/usr/powerpc-wrs-vxworks/wind_base" >> ~/.bashrc
source ~/.bashrc
